# Default state for all rules
default: true

# MD013/line-length - Line length
MD013:
  line_length: 79
  tables: false
  links: false
  code_block_line_length: false
  code_blocks: false

# MD031 - Fenced code blocks should be surrounded by blank lines
# This messes with the mkdocs ...
MD031: false
