repos:
-   repo: https://github.com/python/black
    rev: 23.11.0
    hooks:
    - id: black
      pass_filenames: true
-   repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
    - id: isort
      name: isort (python)
-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: 'v1.7.1'
    hooks:
    -   id: mypy
        additional_dependencies: ['types-requests']
-   repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.1.6
    hooks:
    -   id: ruff
