channels:
  - conda-forge
  - bioconda
  - anaconda
dependencies:
  - perl
  - ca-certificates
  - openssl
  - samtools
  - coreutils # [osx]
  - python>=3.10,<3.12
  - pip
  - r-base=4.3.2
  - r-devtools
  - r-vcfr
  - r-readr
  - r-stringr
  - r-tidyr
  - r-optparse
  - r-seqinr
  - r-dplyr
  - r-plyr
  - r-mass
  - r-tibble
  - r-magrittr
  - bioconductor-genomicranges
  - bioconductor-biostrings
  - bioconductor-iranges
  - bioconductor-rsamtools