name: soprano-dev
channels:
  - conda-forge
  - bioconda
dependencies:
  - perl
  - ensembl-vep=110.1
  - bedtools=2.31.0
  - ca-certificates
  - openssl
  - samtools
  - coreutils # [osx]
  - python==3.11
  - pip