name: soprano-dev
channels:
  - conda-forge
  - bioconda
dependencies:
  - perl
  - ensembl-vep=110.1
  - bedtools=2.31.0
  - python==3.11
  - pip
  - ca-certificates
  - openssl
  - pandas
  - samtools