name: SOPRANO (Dev) Tests

on:
  pull_request:
    branches:
      - python-dev

jobs:
  test:
    name: Development tests
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}
    steps:
      - uses: actions/checkout@v3
      - name: Setup miniconda
        uses: conda-incubator/setup-miniconda@v2
        with:
          auto-update-conda: true
          miniforge-variant: Mambaforge
          channels: conda-forge
          python-version: 3.11
          activate-environment: soprano-dev
          environment-file: src/SOPRANO/ci_linux.yml
          use-mamba: true
      - name: Install SOPRANO
        run: |
          conda activate soprano-dev
          pip install -e .[ci]
      - name: Test conda environment
        run: |
          conda activate soprano-dev
          pytest -s tests/test_configuration
      - name: Test units
        run: |
          conda activate soprano-dev
          pytest -s tests/test_units