name: SOPRANO (Dev) Tests

on:
  push:
    branches:
      - python-dev
      - conda-build-ci
  pull_request:
    branches:
      - python-dev

jobs:
  lint:
    strategy:
      matrix:
        os: ["ubuntu-latest"]
        python-version: ["3.11"]
    name: lint with python ${{ matrix.python-version }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install ruff and black
        run: |
          python -m pip install --upgrade pip
          pip install ruff black
      - name: Lint check with ruff
        run: |
          ruff --target-version=py311 --line-length 79 .
      - name: Style check with black
        run: |
          black ./ --check --line-length 79
  test:
    strategy:
      matrix:
        os: ["ubuntu-latest"]
        python-version: ["3.11"]
    name: test with python ${{ matrix.python-version }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash -l {0}
    steps:
      - uses: actions/checkout@v3
      - name: Setup miniconda
        uses: conda-incubator/setup-miniconda@v2
        with:
          auto-update-conda: true
          miniforge-variant: Mambaforge
          channels: conda-forge
          python-version: 3.11
          activate-environment: soprano-dev
          environment-file: src/SOPRANO/ci_linux.yml
          use-mamba: true
      - name: Install SOPRANO
        run: |
          conda activate soprano-dev
          pip install -e .[ci]
      - name: Test conda environment
        run: |
          conda activate soprano-dev
          pytest tests/test_configuration
      - name: Test units
        run: |
          conda activate soprano-dev
          pytest tests/test_units