name: Lint and style check

on: [ push ]

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11
      - name: Install ruff and black
        run: |
          python -m pip install --upgrade pip
          pip install ruff black
      - name: Lint check with ruff
        run: |
          ruff --target-version=py311 --line-length 79 .
      - name: Style check with black
        run: |
          black ./ --check --line-length 79